repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.2
    hooks:
      - id: poetry-check
        args: ["--lock"]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python -m pytest tests/ -v --cov=src --cov-fail-under=70
        language: system
        pass_filenames: false
        always_run: true
